### DISCUSSION TITLE
I would like to show every commits on ChangeLog

### DISCUSSION THREAD

**Discussion by orcahmlee** [commitizen-tools/commitizen#1277] [Q&A] [answered]
Hi Team,

I used the default settings for `cz ch` but it wouldn't show every commits on the ChangeLog such as `ci`, `test`, `docs`. Is there a configuration can let me choose what committing types can show on the ChangeLog instead of creating a `[tool.commitizen.customize]` section for this slight change?

**Comment by woile** [comment, marked as answer]
I don't think so, you'll have to add a customize, something like:

```toml
[tool.commitizen.customize]
commit_parser = "^((?P<change_type>feat|fix|refactor|perf|docs|style|refactor|BREAKING CHANGE)(?:\\((?P<scope>[^()\r\n]*)\\)|\\()?(?P<breaking>!)?|\\w+!):\\s(?P<message>.*)?"
changelog_pattern = "^((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?):"
change_type_map = {"feat"="Feat","fix"="Fix","refactor"= "Refactor","perf"="Perf","docs"="Docs","style"="Style"}
```
