### DISCUSSION TITLE
version_files not working

### DISCUSSION THREAD

**Discussion by WinnieS0728** [commitizen-tools/commitizen#1382] [Q&A] [answered]
### Description

I'm using commitizen in a expo + react-native project
I do cz init and make a .cz.json like this
```json
{
  "commitizen": {
    "name": "cz_conventional_commits",
    "tag_format": "test-$version",
    "version_scheme": "semver",
    "version": "3.2.4",
    "update_changelog_on_bump": true,
    "version_files": [
      "package.json:version",
      "app.json:expo.version"
    ]
  }
}
```
btw I select `commitizen(default)` not `npm` in source of the version

then I do `cz commit` and `cz bump`
everything finish
version in .cz.json did update
but version in package.json and app.json not update

I'm not sure is it a bug or not,
maybe is something I missed in configuration?
or is a syntax error?

### Steps to reproduce

1. run `cz init`.
2. select 
    - `.cz.json`
    - `cz_conventional_commits(default)`
    - `commitizen(default)`
    - `Y (latest tag)`
    - `semver`
    - `n (correct tag format)`
    - `test-$version`
    - `Y (auto changelog)`
    - `enter (with no hooks)`
3. manually setting `version_files` in .cz.json
4. create new commit
5. run `cz bump`
### Current behavior

after I setting `package.json:version` and `app.json:expo.version`
I think these 2 files will update the correct version
same as the version in .cz.json
but not

### Desired behavior

I want these 3 files update with same and correct version
- package.json (version)
- app.json (expo.version)
- .cz.json (version)

### Environment

Commitizen Version: 4.4.1
Python Version: 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)]
Operating System: Darwin

**Comment by kamilgajekdxc** [comment]
Hello
I have the same problem. Did you manage to fix it?

_Edit_
I managed to solve this problem by trial and error - it's a pity that it is not clearly described in the documentation, or cz bump does not have a debug option, which will indicate problematic elements.

In a situation where I have set the cz.toml configuration file in the root folder
in order for the versions in the listed files to be updated correctly, you should:

- include the version in the cz.toml file

- the version included in cz.toml must match the versions in the other files (in a situation where the versions in the files differ, they will not be updated)

```toml
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "1.6.5-b23"
update_changelog_on_bump = false
major_version_zero = false
annotated_tag = false
version_files = [
    "package.json:version",
    "src/package.json:version",
    "src/pyproject.toml:version"
]
```

Another solution was to have pyproject.toml (or the appropriate manifest for configuration) in the root folder, which contained only information about the version
```toml
[tool.poetry]
version = "1.6.5-b23"
```

cz by default searches for the location in search of the manifest file.
