### DISCUSSION TITLE
Ignore Azure DevOps pull request merge commit message prefix when using cz_conventional_commits

### DISCUSSION THREAD

**Discussion by mateustanaka** [commitizen-tools/commitizen#909] [Q&A]
### Description

We have automation using **commitzen** (cz_conventional_commits) on Azure DevOps but all the pull requests generate a merge commit message that starts with the prefix "**Merged PR XXXX:** " 

![image](https://github.com/commitizen-tools/commitizen/assets/15851963/272bd7b8-ca28-476a-9ed3-f31b391f838a)

I would like avoid to editing all the merge commit message, so would be great to have an option to customize **commitzen** and ignore this prefix for `cz bump` allowing commits message like this:

- `Merged PR 1234: feat: add new language`
- `Merged PR 8462: feat(lang): add Polish language`
- `Merged PR 1346: fix(file.json): adjust boolean property`
- `Merged PR 4732: refactor: rename files`
- `Merged PR 7689: feat(api)!: send an email to the customer when a product is shipped`

### Additional context

There is the customization parameter `schema_pattern` but I couldn't meet my needs. Does anyone know if it is possible to do what I want using this field? Otherwise, this new feature would be good.

**Comment by woile** [comment]
# Options

## Azure config

check if Azure Devops has a way to customize that prompt in order to remove the merge message. On github, if you squash a commit, it won't show the 'merge' message. Open a ticket and ask them to remove that.

## Create your own set of custom rules

Publish your own set of rules: https://commitizen-tools.github.io/commitizen/customization/#2-customize-through-customizing-a-class
The default rule in commitizen is for conventional commits, which start with one of the keywords, not with `Merged`.

## Try to customize the settings

https://commitizen-tools.github.io/commitizen/customization/#2-customize-through-customizing-a-class

You will have to modify a few I think, and the one you need the most is probably `bump_pattern`, it should look something like this:

```toml
[tool.commitizen.customize]
bump_pattern = "^Merged PR \d+: ((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):"
commit_parser = "^Merged PR \d+: ((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!):\s(?P<message>.*)?"
changelog_pattern = "^Merged PR \d+: ((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):"
```

**Reply by mateustanaka** [reply]
Hi @woile thanks for the answer, here is my reply about your options:

## Azure config
Azure DevOps does not have a way to automatically remove the prefix message, there is a feature suggestion at Developer Community opened in 2018:
https://developercommunity.visualstudio.com/t/change-default-title-for-pull-request-commits-to-n-1/365716
A lot of teams need this feature as well, but the discussion is still open.

## Create your own set of custom rules
I am already using the default rule conventional commits in my commitzen 3.10.0 with the following **.cz.json**:
```
{
  "commitizen": {
    "name": "cz_conventional_commits",
    "tag_format": "$version",
    "version_scheme": "semver",
    "version": "1.1.0",
    "update_changelog_on_bump": true
  }
}
```
The script `cz bump` runs every time a Pull Request is completed to the main branch. This works fine but every time before complete I have to manually customize the merge commit message and remove the prefix `Merged PR XXXX: `

## Try to customize the settings
I think this would be the best way to cover this use case. I have tried to build my own configuration file to find the best pattern that follows the conventional commits, I also tried your example but I still did not find a config to successfully cover it. 
If someone already had to define your custom committing and bumping rules in the configuration file that also matches conventional commits and ignore a prefix would help me a lot.

**Reply by woile** [reply]
Can you show how the `.cz.json` looks with the customization I shared? and also the error you get

**Reply by mateustanaka** [reply]
@woile sure, here is my `.cz.json` file with customization you shared:

```
{
  "commitizen": {
    "name": "cz_customize",
    "tag_format": "$version",
    "version_scheme": "semver",
    "version": "1.1.0",
    "update_changelog_on_bump": true,
    "customize": {
      "schema": "<type>(<scope>): <subject>\r\n<BLANK LINE>\r\n<body>\r\n<BLANK LINE>\r\n<footer>",
      "bump_pattern": "^Merged PR \\d+: ((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?):",
      "commit_parser": "^Merged PR \\d+: ((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\\((?P<scope>[^()\r\n]*)\\)|\\()?(?P<breaking>!)?|\\w+!):\\s(?P<message>.*)?",
      "changelog_pattern": "^Merged PR \\d+: ((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?):",
      "bump_map": {
        "feat": "MINOR",
        "fix": "PATCH"
      }
    }
  }
}
```

The above configuration match the message like:

`Merged PR 1443: feat: add new field`

```
mateus@desktop:~/repository (main) $ cz bump --dry-run
bump: version 1.1.0 → 1.2.0
tag to create: 1.2.0
increment detected: MINOR

InvalidVersion GitTag('latest', '3ab3d1c8-2677-46b6-831e-5e9902f2408d', '2023-11-14')
## 1.2.0 (2023-11-14)

### feat

- add new field
```

But does not match when we the commit already in the right conventional commits pattern like:

`feat: add new field`

```
mateus@desktop:~/repository (main) $ cz bump --dry-run
bump: version 1.1.0 → 1.1.0
tag to create: 1.1.0

[NO_COMMITS_TO_BUMP]
The commits found are not eligible to be bumped
```

I need to work with both use cases.

**Reply by woile** [reply]
Ahh, I didn't get that from your messages. You may get repeated messages btw.

You can wrap this chunk in parenthesis with a question mark, to make it optional, and leave the rest the same.
```
(Merged PR \\d+: )?
```
Pay attention to the space after the colon.

I recommend also testing all the possibilities in regex101 with the python backend

**Reply by mateustanaka** [reply]
I have tried some options like it already. 

`"bump_pattern": "^(Merged PR \\d+: )?((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?):"`

`"bump_pattern": "^(Merged PR \\d+: )?(fix|feat): .+$"`

`"bump_pattern": "^(Merged PR \\d+: )?(feat|fix)"`

But for all those patterns I got an error from commitizen cz bump:

`Merged PR 1234: feat: add new field` - NOK (NO_COMMITS_TO_BUMP)

`feat: add new field` - NOK (Error)

```
mateus@desktop:~/repository (master) $ cz bump --dry-run
Traceback (most recent call last):
  File "/home/mateus/.local/bin/cz", line 8, in <module>
    sys.exit(main())
  File "/home/mateus/.local/lib/python3.10/site-packages/commitizen/cli.py", line 565, in main
    args.func(conf, arguments)()
  File "/home/mateus/.local/lib/python3.10/site-packages/commitizen/commands/bump.py", line 218, in __call__
    increment = self.find_increment(commits)
  File "/home/mateus/.local/lib/python3.10/site-packages/commitizen/commands/bump.py", line 126, in find_increment
    increment = bump.find_increment(
  File "/home/mateus/.local/lib/python3.10/site-packages/commitizen/bump.py", line 35, in find_increment
    if re.match(match_pattern, found_keyword):
  File "/usr/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Reply by mateustanaka** [reply]
Hi @woile Do you know if there is any workaround for it or should we convert it to a bug?

**Reply by woile** [reply]
What do you want to make a bug?

**Reply by woile** [reply]
These regex work well for me:

```
^(Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):

^(Merged PR \d+: )?((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!):\s(?P<message>.*)?

^(Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):
```

**Reply by mateustanaka** [reply]
The regex format is ok for regex101 but when we use it in the commitizen we are facing two issues:

- Throws an exception when commit message is `fix: adjust format field`
- Do commits eligible found to be bumped when commit is `Merged 1234: fix: adjust format field`

![image](https://github.com/commitizen-tools/commitizen/assets/15851963/ae7e2e7e-d0d9-4fbe-8d5e-2c1019fced61)

But I expect cz bump work for both commits scenarios.

**Reply by woile** [reply]
Can you try using `.cz.toml` instead of the `.json`? That way we can discard is not a json problem

**Reply by mateustanaka** [reply]
I tried using `.cz.toml` but I got the same errors:

![image](https://github.com/commitizen-tools/commitizen/assets/15851963/468cbd44-665c-419b-bae2-dd22d115d7e1)

**Reply by mgeorgebrown89** [reply]
I am also dealing with a very similar situation. When using the defaults, my pipeline will update the version according to the commits just fine, but it doesn't include anything in the changelog other than the numbers. If I manually change the merge commit, it includes everything. I've tried to tweak the regex a bit, but this is the current state of my .cz.yaml
```
---
commitizen:
  bump_message: release $current_version -> $new_version [skip ci]
  name: cz_customize
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.1.5
  version_scheme: semver
  customize:
    bump_pattern: "^(Merged PR \\d+: )?((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?): "
    commit_parser: "^(Merged PR \\d+: )?((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\\((?P<scope>[^()\\r\\n]*)\\)|\\()?(?P<breaking>!)?|\\w+!):\\s(?P<message>.*)?"
    changelog_pattern: "^(Merged PR \\d+: )?((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?): "
```
I get this error when running `cz bump`
```
Traceback (most recent call last):
  File "/home/michael/.local/bin/cz", line 8, in <module>
    sys.exit(main())
  File "/home/michael/.local/lib/python3.10/site-packages/commitizen/cli.py", line 570, in main
    args.func(conf, arguments)()
  File "/home/michael/.local/lib/python3.10/site-packages/commitizen/commands/bump.py", line 218, in __call__
    increment = self.find_increment(commits)
  File "/home/michael/.local/lib/python3.10/site-packages/commitizen/commands/bump.py", line 127, in find_increment
    increment = bump.find_increment(
  File "/home/michael/.local/lib/python3.10/site-packages/commitizen/bump.py", line 35, in find_increment
    if re.match(match_pattern, found_keyword):
  File "/usr/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Reply by mgeorgebrown89** [reply]
I've switched to using a toml file
```
[tool.commitizen]
name = "cz_customize"
tag_format = "v$version"
version_scheme = "semver"
version = "0.1.5"
update_changelog_on_bump = true

[tool.commitizen.customize]
bump_pattern = "^Merged PR \\d+: ((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?):"
commit_parser = "^Merged PR \\d+: ((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\\((?P<scope>[^()\\r\\n]*)\\)|\\()?(?P<breaking>!)?|\\w+!):\\s(?P<message>.*))?"
changelog_pattern = "^Merged PR \\d+: ((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?):"
```
It complained if I was using single backslashes like `Failed to parse .cz.toml: Invalid character 'd' in string at line 10 col 29` which is why I added the extra escape characters. 

I can get `cz bump` to at least not complain when there's no commits, but when I try to commit something it gives the following error _still_
```
Traceback (most recent call last):
  File "/home/michael/.cache/pre-commit/repohleepac6/py_env-python3/bin/cz", line 8, in <module>
    sys.exit(main())
  File "/home/michael/.cache/pre-commit/repohleepac6/py_env-python3/lib/python3.10/site-packages/commitizen/cli.py", line 570, in main
    args.func(conf, arguments)()
  File "/home/michael/.cache/pre-commit/repohleepac6/py_env-python3/lib/python3.10/site-packages/commitizen/commands/check.py", line 74, in __call__
    ill_formated_commits = [
  File "/home/michael/.cache/pre-commit/repohleepac6/py_env-python3/lib/python3.10/site-packages/commitizen/commands/check.py", line 77, in <listcomp>
    if not self.validate_commit_message(commit.message, pattern)
  File "/home/michael/.cache/pre-commit/repohleepac6/py_env-python3/lib/python3.10/site-packages/commitizen/commands/check.py", line 148, in validate_commit_message
    return bool(re.match(pattern, commit_msg))
  File "/usr/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.10/re.py", line 302, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
```

**Reply by mgeorgebrown89** [reply]
> These regex work well for me:
> 
> ```
> ^(Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):
> 
> ^(Merged PR \d+: )?((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!):\s(?P<message>.*)?
> 
> ^(Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):
> ```

To clarify, @woile , when you say these work well for you, do you mean they work as regex expressions or within the context of commitizen? I can't get any version of these expressions to work when attempting to customize the .cz.toml file. It appears the underlying python doesn't recognize them as proper regex or something. I'm attempting to troubleshoot now but any further assistance is greatly appreciated. :)

**Reply by mgeorgebrown89** [reply]
oooh this might be related to pre-commit. I noticed I could get it working when using `cz bump` from the command line, but when I run it as part of pre-commit, it fails. But precommit doesn't use my customization I'm guessing.

**Reply by mgeorgebrown89** [reply]
Ok well it appears that error is because the check command was excepting there to be something in `schema_pattern` and if you customize the config there isn't a default anymore. Now my .cz.toml looks like this, but I'm still only getting the version number to update in the changelog, none of the commits show up.
```
 [tool.commitizen]
# name = "cz_customize"
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "0.1.7"
update_changelog_on_bump = true
bump_message = "release $current_version -> $new_version [skip ci]"

[tool.commitizen.customize]
schema_pattern = '"<type>(<scope>): <subject>\r\n<BLANK LINE>\r\n<body>\r\n<BLANK LINE>\r\n<footer>"'
bump_pattern = '^(Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):'
commit_parser = '^(Merged PR \d+: )?((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!):\s(?P<message>.*))?'
changelog_pattern = '^(Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):'
```

**Reply by woile** [reply]
```toml
[tool.commitizen]
name = "cz_customize"
tag_format = "v$version"
version_scheme = "semver"
version = "0.1.7"
update_changelog_on_bump = true
bump_message = "release $current_version -> $new_version [skip ci]"

[tool.commitizen.customize]
schema_pattern = '"<type>(<scope>): <subject>\r\n<BLANK LINE>\r\n<body>\r\n<BLANK LINE>\r\n<footer>"'
bump_pattern = '^(?:Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):'
commit_parser = '^(?:Merged PR \d+: )?((?P<change_type>feat|fix|refactor|perf|BREAKING CHANGE)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!):\s(?P<message>.*)?'
changelog_pattern = '^(?:Merged PR \d+: )?((BREAKING[\-\ ]CHANGE|\w+)(\(.+\))?!?):'
```

This seems to work well for me, I use `?:` in the first group to avoid capturing it.

I tested it with this script:

```
#!/bin/bash -ex
git init

touch c
git add c .cz.toml
git commit -am "Merged PR 1234: feat: add new language"

cz bump --yes

touch b
git add b
git commit -am "Merged PR 8462: feat(lang): add Polish language"

cz bump
```
