### ISSUE TITLE
Support version_files together with version_provider=poetry

### ISSUE THREAD

**Issue by jzazo** [commitizen-tools/commitizen#1066]
### Description

I have a monorepo with multiple poetry projects. I would like configure `version_provider=poetry` and `version_files` in `.cz.toml` in the root. When I run `cz bump` all `pyproject.toml` files should be updated.

### Possible Solution

```toml
[tool.commitizen]
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "poetry"
version_files = [ "paths/to/pyproject.tomls"]
```

### Additional context

I figured that following works, so maybe this request could be closed:

```toml
[tool.commitizen]
tag_format = "v$version"
version = "0.1.0"
version_scheme = "pep440"
version_files = [ "paths/to/pyproject.toml:version"]
```
