### ISSUE TITLE
Support pattern paths in `version_files`

### ISSUE THREAD

**Issue by jzazo** [commitizen-tools/commitizen#1067]
### Description

It would be nice to support patterns when specifying `version_files`.

### Possible Solution

```toml
[tool.commitizen]
tag_format = "v$version"
version = "0.1.0"
version_scheme = "pep440"
version_files = [ "**/pyproject.tomls"]
```
