### ISSUE TITLE
commitizen check failed using the "cz-conventional-gitmoji"

### ISSUE THREAD

**Issue by atiasn** [commitizen-tools/commitizen#1141]
### Description

commitizen check failed using the "cz-conventional-gitmoji"

### Steps to reproduce

1. conda create virtualenv
2. conda activate the virtualenv
3. poetry add commitizen
4. poetry add cz-conventional-gitmoji
5. edit .pre-commit-config.yaml
```yaml
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
```
6. edit pyproject.toml
``` toml
[tool.commitizen]
name = "cz_gitmoji"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true
version_files = ["pyproject.toml:^version"]
bump_message = "🔖 bump(release): $current_version → $new_version"
```
8. poetry show
```shell
# poetry show | grep commi
commitizen              3.27.0      Python commitizen client tool
cz-conventional-gitmoji 0.3.2       A commitizen plugin that combines gitmo...

```

### Current behavior

```shell
commitizen check.........................................................Failed
- hook id: commitizen
- exit code: 1

The committer has not been found in the system.

Try running 'pip install cz_gitmoji'
```

```shell
# which cz
/home/clei/miniconda3/envs/paimon/bin/cz
                         
Python 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> importlib.import_module("cz_gitmoji")
<module 'cz_gitmoji' from '/home/clei/miniconda3/envs/paimon/lib/python3.11/site-packages/cz_gitmoji/__init__.py'>

```

### Desired behavior

The "commitizen check" should be passed

### Environment

``` bash
# cz version --report
Commitizen Version: 3.27.0
Python Version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
Operating System: Linux
```

**Comment by Lee-W** [comment]
AFAIK, pre-commit setup a new env for each hook so you'll need to set "additional_dependencies", but this is indeed something we can improve in the documentation

**Comment by atiasn** [comment]
@Lee-W Thanks, I set the `additional_dependencies` in the `.pre-commit-config.yaml` and it ran successfully.
```yaml
repo: https://github.com/commitizen-tools/commitizen
rev: v3.27.0
hooks:
  - id: commitizen
    stages: [commit-msg]
    additional_dependencies: ["cz-conventional-gitmoji"]
```
