### ISSUE TITLE
Release after dev release results in error

### ISSUE THREAD

**Issue by peterdragun** [commitizen-tools/commitizen#1180]
### Description

After creating a dev release I am not able to create a regular release. Issue can be worked around if I remove the dev release from the changelog.

Also based on the [documentation](https://commitizen-tools.github.io/commitizen/tutorials/dev_releases/#about) one would expect `X.Y.devN` version to work, but that is not the case.

### Steps to reproduce

1. Create a dev release by running:
`cz bump --devrelease 1`
Changelog now contains entry for this dev release
2. Create a regular release by running:
`cz bump`

### Current behavior

Error message:
```
change: Update version to 4.8.0
tag to create: v4.8.0
increment detected: MINOR

No tag found to do an incremental changelog
```
Seems like the only issue here is the changelog parsing.

### Desired behavior

Commitizen should be able to parse the changelog and create a new release. Remove the dev release from the changelog and add changes to the new release.

### Environment

Commitizen version: 3.27.0
Python version: 3.12.3
OS: macOS Sonoma 14.5

Config - pyproject.toml:
```toml
[tool.commitizen]
    version = "4.8.0.dev5"
    update_changelog_on_bump = true
    tag_format = "v$version"
    changelog_start_rev = "v4.2.1"
    changelog_merge_prerelease = true
    annotated_tag = true
    bump_message = "change: Update version to $new_version"
    version_files = [
        "esptool/__init__.py:__version__"
    ]
    change_type_order = [
        "BREAKING CHANGE",
        "New Features",
        "Bug Fixes",
        "Code Refactoring",
        "Performance Improvements"
    ]

[tool.commitizen.change_type_map]
    feat = "New Features"
    fix = "Bug Fixes"
    refactor = "Code Refactoring"
    perf = "Performance Improvements"
```
