### ISSUE TITLE
Commit messages not added to CHANGELOG.md from pull request in Azure DevOps

### ISSUE THREAD

**Issue by paul-e-martin** [commitizen-tools/commitizen#1202]
### Description

I have the commit messages correct following the fix:/feat: convention
I have the following pipeline that runs on a pull request into main
```yaml
trigger:
  - main

stages:
- stage: SemanticVersion
  jobs:
  - job: SemanticVersion
    displayName: Bump Semantic Version
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: |
          pip install commitizen
        displayName: 'install Commitizen'

      - task: PowerShell@2
        displayName: 'Bump version'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Configuring git author info.." -ForegroundColor Cyan
            git config user.email "Azure DevOps pipeline"
            git config user.name "Azure.Devops@pipeline.com"

            Write-Host "Running Commitizen bump.." -ForegroundColor Cyan
            cz bump --check-consistency --yes
            git push --tags origin HEAD:main
```
The tags are correctly created, and the CHANGELOG.md gets updated, but only with the version and date information. The commit messages aren't there
![image](https://github.com/user-attachments/assets/5ec4867d-caa6-4a7f-92de-db0e3369e3dc)

I believe the issue is that when creating a Pull Request in Azure DevOps, it prefixes the commit message with "Merged PR ###:"
![image](https://github.com/user-attachments/assets/55b53d43-6080-4563-86fa-9e5c7e22b69d)
If i override the commit message to just the format of fix: it works, but then i also need to remove the entry from the "comments field" (larger box), otherwise i get duplicate entries in CHANGELOG.md

I may have missed an obvious setting somewhere, as completely new to using Commitizen, so would appreciate any assistance.

### Steps to reproduce

Create a pull request into an Azure DevOps repo that triggers the above pipeline. 

### Current behavior

Tags and CHANGELOG created/updated, but the CHANGELOG.md doesn't include the commit messages, so only have the version and date

### Desired behavior

To have the commit messages included in the CHANGELOG.md

### Environment

Running on an Azure hosted Ubuntu agent
Commitizen version 3.28.0
