### ISSUE TITLE
Good bug title tells us about precise symptom, not about the root cause.

### ISSUE THREAD

**Issue by gsemet** [commitizen-tools/commitizen#1315]
### Description

When generating a changelog, some commits does not appear in the log

### Steps to reproduce

I have these commits in my history:
```
* b6a9e13 - (tag: 0.19.2, origin/dev/win11, dev/win11) ci: fix quality evidence package (2 weeks ago) <Gaetan Semet>
* 1f3f152 - ci: rework release process (2 weeks ago) <Gaetan Semet>
* b932d80 - ci: switch to CI_VM_WIN tag (2 weeks ago) <Gaetan Semet>
* 4899b0d - doc: update install notification (2 weeks ago) <Gaetan Semet>
* 52bd731 - (tag: 0.19.1) doc: update documentation for 0.19 (3 weeks ago) <Gaetan Semet>
* 70f8611 - (tag: 0.19.0) fix: package metadata becomes package manifest (3 weeks ago) <Gaetan Semet>
```

Command line:
cz changelog -file-name docs/source/changelog.md   --unreleased-version UNRELEASED_VERSION

### Current behavior

commits does not appear

```
### Version [0.19.2](https://my.gitlab.server/path/to/project/-/releases/0.19.2) (2024-12-03)

### Version [0.19.1](https://my.gitlab.server/path/to/project/-/releases/0.19.1) (2024-11-28)

### Version [0.19.0](https://my.gitlab.server/path/to/project/-/releases/0.19.0) (2024-11-27)
```

### Desired behavior

```
### Version [0.19.2](https://my.gitlab.server/path/to/project/-/releases/0.19.2) (2024-12-03)

**Documentation*: 
- update install notification

**CI**:
- fix quality evidence package
- rework release process
- switch to CI_VM_WIN tag

### Version [0.19.1](https://my.gitlab.server/path/to/project/-/releases/0.19.1) (2024-11-28)

**Doc**:
-  update documentation for 0.19
```

It is like the "ci", "doc" prefixes causes the lines to be ignored in the changelog

### Environment

```
$ cz version
4.1.0
```

**Comment by gsemet** [comment]
No idea why "ci", "doc", "perf" commit types does not appear in the changelog ? is there nobody else that has this issue ?

**Comment by gsemet** [comment]
ok, so it seems like the default configuration for the conventional_commit pattern drop some commits.

I cannot override some settings from this model, how can i dump the current configuration to a file so that i change some of the settings ?

**Comment by gsemet** [comment]
I managed to get my lost commits using my own configuration in pyproject.toml

```toml
[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
commit_parser = '^((?P<change_type>feat|fix|refactor|perf|style|test|ci|build|doc|chore|BREAKING CHANGE)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!):\s(?P<message>.*)?'
change_type_order = ["BREAKING CHANGE", "feat", "fix", "refactor", "perf", "test", "style", "doc", "ci", "build", "chore"]
```
