### ISSUE TITLE
Allow bump calculate the next version from git log

### ISSUE THREAD

**Issue by pablodgonzalez** [commitizen-tools/commitizen#1374]
### Description

Currently, when skip commits and no using tags at all (in my use case, I bump the version with each commit) always get a MAYOR bump, but my commit is not a BREAKING CHANGES.

### Possible Solution

When sip using tags at all, use the git log to read the commit messages and calculate the next version in bump

**Comment by Lee-W** [comment]
Hi @pablodgonzalez , I don't quite understand. Could you please provide an example for helping us understand? Thanks!

**Comment by pablodgonzalez** [comment]
Sure, My team use commitizen for the wizard to prepare the commit message, to check the commit message and to do the bump version.
But for the last one we use pre-commit to
```yaml
- repo: local
    hooks:
      - id: cz-bump
        name: "📝 commitizen · Bump version"
        entry: bash -c 'cz bump --increment PATCH --files-only --yes && git add .cz.toml CHANGELOG.md main/settings/base.py'
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - commit-msg
```
rigth now, we force a PATCH bump, because the bump use the tag version to check the last version and calculate what kind of increment to do.
Since we do not use tags, instead would like to use just the kind on commit (breaking change, feat, fix, etc) but those only work when tagging
