### ISSUE TITLE
commitzen modifies the output from pre-commit and makes it hard to see

### ISSUE THREAD

**Issue by guihao-liang** [commitizen-tools/commitizen#197]
## Description
my cz version is `1.22.2`.

![image](https://user-images.githubusercontent.com/14238915/83477201-981ea580-a447-11ea-88c2-191d6e81bc7d.png)

1. the commit message color is hard to see
2. the pre-commit color is altered, the original should be below:
![image](https://user-images.githubusercontent.com/14238915/83477265-c2706300-a447-11ea-854f-7af64d5d6ea2.png)
Besides that, why the color from the subprocess is changed to `red`?

## Possible Solution

restore the terminal color setting before delegating calls to subprocess.

## Additional context

minimum reproducible setting:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
```

## Related Issue
If applicable, add link to existing issue also help us know better.
