### ISSUE TITLE
[Feature Request] Contextual help on selections

### ISSUE THREAD

**Issue by blaggacao** [commitizen-tools/commitizen#202]
Provide contextual help:
```toml
[[tool.commitizen.customize.questions]]
type = "list"
choices = ["foo", "barbuz"]
foo.message = "explanation to foo"
barbuz.message = "explanation to barbuz"
```
```shell
cz commit                             
...
foo     - explanation to foo
barbuz  - explanation to barbuz
```
Help message alignment + at least two spaces before `-` (sic!)

Without it this tool is barely user friendly. Still, great tool!

**Comment by blaggacao** [comment]
Btw, I don't consider this a questionary upstream task. Questionary implements choices, choice metadata is a concept of commitizen.

**Comment by Lee-W** [comment]
Hi! Thanks for the suggestion! I'm not sure whether we should make this behavior default. But it's definitely good to have this as an option or a plugin

**Comment by blaggacao** [comment]
It should be default, as there is no usability reason not to, besides braking the API. So maybe for a stable version bump?

**Comment by Woile** [comment]
I don't follow the proposal. 

How is it now, and what would you expect?

Is it related only to the customization through toml?

Thanks!

**Comment by Lee-W** [comment]
The following is what we currently generate.

```txt
foo - explanation to foo
barbuz - explanation to barbuz
```

The following is the proposed behavior

```txt
foo     - explanation to foo
barbuz  - explanation to barbuz
```

It's what I understand. @blaggacao Please correct me if I'm wrong 🙂

**Comment by Lee-W** [comment]
As for whether we should make it a default. I'm a bit against it. It looks more like a personal preference to me. I'm ok with either format. @Woile What do you think?

But I do agree to add this to commitizen. 🚀

**Comment by Woile** [comment]
I'm not sure, that's why I'm asking. What I understand is that currently we have:

```toml
[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = ["feature", "bug fix"]
message = "Select the type of change you are committing"
```

so, it's not possible to have a `key` **and** `value` in the `choices`. So his proposal is to make it possible:

```toml
[[tool.commitizen.customize.questions]]
type = "list"
choices = ["foo", "barbuz"]
foo.message = "explanation to foo"
barbuz.message = "explanation to barbuz"
```

but I may be wrong, and his proposal is about styling.

**Comment by blaggacao** [comment]
Jep, as far as the current docs and what Inpoked around in the code, there is a misunderstanding in this discussion.

My state of knowledge is:

We have:
```
foo
barbuz
```

We want:
```
foo     - explanation to foo
barbuz  - explanation to barbuz
```
This is how the js implementation presents the choices by default. UX wise proper column alignment makes a difference such as respecting min 2 spaces, like in proper formatted code comments.

**Comment by blaggacao** [comment]
Do I correcly perceive, that, after sheding light on the initial misunderstanding, there is consensus on this feature request? 

Maybe we could use a flag for it signal it's state, so that implememtation can be unblocked.

What do you guys think?

**Comment by Woile** [comment]
To be honest, I don't like the idea atm. Styling is a matter of opinion and I don't think it breaks usability.

For this kind of cases (personal taste), you can always build a custom `cz`, we [have a template](https://github.com/commitizen-tools/commitizen_cz_template) which can assist you in reaching your desired goal.

Did you try doing this?

```toml
[[tool.commitizen.customize.questions]]
type = "list"
choices = [
  {value = "foo", name = "foo     - explanation to foo"}, 
  {value = "barbuz", name = "barbuz  - explanation to barbuz"}
]
```

It would output this (when doing `cz commit`):
```
foo     - explanation to foo
barbuz  - explanation to barbuz
```
