### ISSUE TITLE
[Feature Request] Support for PEP 621

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#212]
## Description
[PEP 621](https://www.python.org/dev/peps/pep-0621/) define `version` under `project`.  e.g.,

```toml
[project]
name = "spam"
version = "2020.0.0"
description = "Lovely Spam! Wonderful Spam!"

```

Currently, we might define `version` for multiple tools. For example, if we use `poetry` and `commitizen` in the same project, we'll have to make sure we sync up these two values. Once this is supported by both `poetry`, `commitizen`  and even other tools. We no longer need to worry about syncing problems.

## Possible Solution
Use the `version` under `project` if it exists.

## Related Issue
If applicable, add link to existing issue also help us know better.
