### ISSUE TITLE
[Feature Request] Add command to generate only recent changelog changes

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#225]
## Description
So a normal workflow would be to automatically release to GitHub after a new version tag is created. That part works, but there is no good way to include the recent changelog additions as the body paragraph of the GitHub release.

To release with github actions, you do something like
```yaml
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  github_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Release to GitHub
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
        "my new changes here"
        draft: false
        prerelease: false
```

Currently, and please correct me if I'm wrong, there is no way to automatically fill "body" with the recent additions to the changelog

## Possible Solution
Introduce an option to `cz changelog` that would allow to to generate the most recent version so you could say something like this:
```yaml
    # so we can use it as the github release body
    - name: Store recent changelog changes
      run: |
        echo ::set-env name=CHANGELOG::$(cz changelog --dry-run --recent)

    - name: Release to GitHub
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ env.CHANGELOG }}
        draft: false
        prerelease: false
```
