### ISSUE TITLE
Pre-commit hook requires username and password to intialize

### ISSUE THREAD

**Issue by jtpavlock** [commitizen-tools/commitizen#232]
## Description
Running the pre-commit hook given 
```yaml
  - repo: https://github.com/commitizen-tools/commitizens
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
```

Now prompts for a username and password to when "initializing environment"

## Steps to reproduce
1. Delete pre-commit cache in ~/.cache/pre-commit
2. run `pre-commit run -a`

## Desired behavior

**Screenshots**
![image](https://user-images.githubusercontent.com/26807251/88465831-c9d24c80-ce8b-11ea-87f8-0d0274a08401.png)
top is before before the commitizen hook is added to `.pre-commit-config.yaml` bottom is after. As you can see, all my other hooks work fine, I'm not sure what changed to cause this.

## Environment

- commitizen version: 1.23.3
- python version: 3.8.2
- operating system: ubuntu 20.04
