### ISSUE TITLE
cz bump -ch doesn't create commit, tag and changelog

### ISSUE THREAD

**Issue by sanzoghenzo** [commitizen-tools/commitizen#240]
## Description

I really don't know if it's a bug or it's me that I don't understand how this works...

It seems to me that my `cz bump -ch` only changes the version in my files, but doesn't do the other stuff I wish it would have done:

- generate the changelog;
- create a commit for the version bump and the changelog;
- create a tag for that commit.

## Steps to reproduce

1. Set up a python project with poetry, and add this to `pyproject.toml`:
    ```toml
    [tool.commitizen]
    version = "0.1.0"
    version_files = ["pyproject.toml:version"]
    tag_format = "v$version"
    bump_message = "build: release $current_version → $new_version"
    ```
2. commit some code and manually create a v0.1.0 tag
3. change something and use `cz c` to commit them
4. run `cz bump -ch`

## Current behavior

```shell
$ cz bump -ch
message
tag to create: v0.2.0
increment detected: MINOR
```

- version is correctly bumped in `pyproject.toml`;
- no commit is created (as you can see `message` is displayed instead of the expected bump message; this occurs even if I remove the custom `bump_message` from `pyproject.toml`);
- changelog is not updated;
- no tag is created.

## Desired behavior

What I listed on the description.

Note that `cz changelog --dry-run` result is somewhat good (I don't know why there are `'`s in the v.0.1.0 title, but its section is empty because the I messed up the commit message on MR merge).

```markdown
## Unreleased

### Feat

- **api**: add new endpoint

## 'v0.1.0 (2020-07-27')
```

## Environment

- commitizen version: 2.0.0
- python version: 3.7.0 (miniconda)
- operating system: Windows 10 64 bit 1909

I also tried this on a WSL ubuntu 20.04 with python 3.7.8, same problem.
