### ISSUE TITLE
Default parameters for confirm type question not working in .cz.toml

### ISSUE THREAD

**Issue by FelixAbrahamsson** [commitizen-tools/commitizen#263]
## Description
I'm trying to set the default parameter for a confirm type question to No/False, but no matter the format I try (which has to be a string) I can't get it to work.

## Steps to reproduce
In my .cz.toml I have something like this
```
[[tool.commitizen.customize.questions]]
type = "confirm"
name = "breaking"
default = "False"
message = "Is this a breaking change?"
```
which still results in the default being Y. I've tried other variants (false, no, n, No, N, non-string input) but nothing seems to work.

## Current behavior
The default is yes no matter what I try to set.

## Desired behavior
I expect the default to change to No.

## Environment
- commitizen version: 2.1.0
- python version: 3.8
- operating system: Ubuntu 18.04

**Comment by Lee-W** [comment]
@FelixAbrahamsson  The following config works for me. Please try again with this. Let me know if it does not work for you

```toml
[[tool.commitizen.customize.questions]]
type = "confirm"
name = "breaking"
default = false
message = "Is this a breaking change?"
```
