### ISSUE TITLE
Run only on a specific branch

### ISSUE THREAD

**Issue by girardinsamuel** [commitizen-tools/commitizen#266]
## Description
I don't know if there is a way to achieve this now or if I am not using commitizen correctly, but I would like to lint commits on `master` branch only (where I will  also bump releases and generate changelog).
For development (other) branches, I would like to be able to commit without checking commit messages, but before validating the PR, force to rewrite the history of the branch if it does not follow commitizen rules.

## Possible Solution
I was thinking about adding commitizen pre-commit hook but that should run only on PR and master (through CI) and not in local development in other branches than master. Is there a new feature here or I am misusing commitizen ?

Thank you in advance ! 👍

**Comment by Woile** [comment]
You don't need `pre-commit` for that. Just run the commands yourself in your pipelines.
If you are using github actions, you'd have 2 actions, one for pull_request and one for release.

```yaml
name: Pull request

on: [pull_request]
jobs:
  python-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run commitizen check
      run: |
        cz check --rev-range $GITHUB_SHA..HEAD
```
most of the CI provide an enviromental variable with the hash that triggered the CI.

For `Release` you'd trigger on master, and you can run the check again and then run `cz bump --changelog`
