### ISSUE TITLE
lightweight tags create no "create event" in github actions

### ISSUE THREAD

**Issue by diefans** [commitizen-tools/commitizen#271]
## Description
Commitizen creates only lightweight tags, which are not creating a "create event" in github actions.

## Steps to reproduce
https://github.com/commitizen-tools/commitizen/blob/master/commitizen/git.py#L49

## Current behavior
A lightweight tag created by commitizen does not lead to a usefull event in github actions.

## Desired behavior
Create an annotated tag, e.g. `git tag -a <version> -m <version>`. This should be at least a configurable option IMHO.

## Environment
- commitizen version: master

**Comment by Woile** [comment]
thanks for the finding! some questions, how did you find this problem? could you point the GA documentation where they mention lightweight tag don't create events? I couldn't find it.

I'll run some tests in to verify it as well :muscle:

**Comment by diefans** [comment]
I have no documentation at hand. But as far as I know, lightweight tags are not "real" objects in git and have also no creation date. You can see this via `git for-each-ref` where the objecttype of a lightweight tag is `commit` and for an annotated tag it is `tag` (also find this in my unit test).
So basically I found this by trying github actions to do something after tag creation (see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create), but there was no event triggered after commitizen created the "tag". So I just created a dummy annotated tag and my workflow was running - so I came to that conclusion....

**Comment by Lee-W** [comment]
We use the following syntax to detect release which might be the reason why we did not encounter such problem.

```yaml
on:
  push:
    tags:
      - 'v*'
```

But I think it's a feature we could have. Thanks for great work 🙂 I'll also run some test to verify it.

**Comment by diefans** [comment]
@Lee-W I do not really understand how this is working for you:
I have a job running basically the example in your docs:
```
  bump-version:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    needs:
      - build
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
The job appears to work fine: ```
...
Configuring git user and email...
Runnung cz...
bump: version 0.2.1 → 0.2.2
tag to create: 0.2.2
increment detected: PATCH

Done!
Pushing to branch...
To https://github.com/*/*.git
   f76d488..8bdc82d  HEAD -> master
 * [new tag]         0.2.2 -> 0.2.2
Done.
```

I also have a debug workflow: ```
name: debug
on:
  push:
    tags:
      - "*"
  create:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.ref }}
      - run: echo ${{ toJSON(github.event) }}
```
but this gets never triggered after the "tag" is "pushed" via the bump-version job.
