### ISSUE TITLE
Commitizen puts in extra newlines when processing pyproject.toml.

### ISSUE THREAD

**Issue by 7kachika** [commitizen-tools/commitizen#355]
## Description
`commitizen` puts in extra newlines when processing `pyproject.toml`.

## Steps to reproduce
Run `cz init` or `cz bump`.

## Current behavior
The following is the `pyproject.toml` generated by `cz init`:
```toml
[tool.commitizen]


name = "cz_conventional_commits"


version = "0.0.1"

tag_format = "$version"

```

## Desired behavior
`pyproject.toml`:
```toml
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "$version"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13810485/109131193-89261300-778d-11eb-8d6f-ae5ad4bda536.png)

## Environment

- commitizen version: 2.15.2
- python version: 3.9.2
- operating system: Windows 10 Version 2004
