### ISSUE TITLE
cz changelog --no-prereleases

### ISSUE THREAD

**Issue by Yajo** [commitizen-tools/commitizen#364]
## Description
Sometimes I don't want prereleases to be displayed in the changelog. For me, commits in a prerelease should land in the Unreleased section. Then, once the final release is out, changes from all involved prereleases should appear in the final release.

## Possible Solution

Add `--no-prereleases` to `cz changelog`, so prerelease tags are simply ignored.

**Comment by nbrugger-tgm** [comment]
This sounds very applealing. Especially if #415 is implemented as it would lead to an empty release.

## Scenario
```
1.2.3
commit feat: 1
bump -pr beta -> 1.3.0b
commit fix: 2
bump -pr rc -> 1.3.0rc
bump (prod) -> 1.3.0     (This would be allowed after #415)
```

Current changelog impl.
```
# 1.3.0
# 1.3.0rc
### Fix
* 2
# 1.3.0b
### Features
* 1
```

So the release itself is completely empty

**Comment by bhelgs** [comment]
Maybe an alternative would be to just allow a configurable regex this way a user can select any patterns they like for their changelogs?

It would sort of parallel what currently exists for confguring the `bump`
``` toml
[tool.commitizen]
tag_format = "v$major.$minor.$patch$prerelease"
```

but instead configure the `changelog` generation:
``` toml
[tool.commitizen]
tag_format = "v$major.$minor.$patch$prerelease"
tag_parser = "^v[0-9]*\.[0-9]\.[0-9]"
```

The default value would be ( `.*`) since commitizen is matching every tag at the moment.
