### ISSUE TITLE
Bump only updates the first match in a version_file

### ISSUE THREAD

**Issue by pedrorrivero** [commitizen-tools/commitizen#383]
## Description
Since version 2.17.3 `cz bump` seems to only update the first match it finds in any given version_file.

## Steps to reproduce
1. Set up *pyprject.toml*, in my case I am using commitizen as well as poetry, each of which with a version entry in its setup.
2. Run `cz bump`.

## Current behavior
Only the first match gets updated.

## Desired behavior
All matching lines should be updated it was before version 2.17.3 (<2.17.3).

## Environment
- commitizen version: >=2.17.3
- python version: Python 3.8.6
- operating system: Darwin

**Comment by Lee-W** [comment]
Hi, I've just tried on 2.17.3 but failed to reproduce the error. Could you provide your example? The following was the `pyproject.toml` file I tried.

```toml
[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.2"
tag_format = "$version"
version_files = [
    "pyproject.toml:version"
]

[tool.poetry]
name = "test"
version = "0.0.2"
description = ""

[tool.poetry.dependencies]
python = "^3.8"
pytest = {version = "^0.0.2"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

**Comment by pedrorrivero** [comment]
Sure! This comes from my project [QRAND](https://github.com/pedrorrivero/qrand) if you need any more information. I have currently downgraded to version 2.17.2, but this should reproduce it:

```toml
[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.commitizen]
name = "cz_conventional_commits"
bump_message = "bump: version $current_version → $new_version"
version_format = "$version"
version = "0.3.0a0"
version_files = [
    "qrand/__init__.py:__version__",
    "tests/test_qrand.py:__version__",
    "pyproject.toml:version",
    "QRAND.bib:version"
]
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.poetry]
name = "qrand"
version = "0.3.0a0"
description = "A multiprotocol and multiplatform quantum random number generation framework"
readme = "README.md"
homepage = "https://github.com/pedrorrivero/qrand"
authors = ["Pedro Rivero <pedro.rivero.ramirez@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.19.4"
randomgen = "^1.19.3"
qiskit = { version = "^0.25.0", optional = true }
cirq = { version = "^0.10.0", optional = true }
qsharp = { version = "^0.15.2103", optional = true }

[tool.poetry.extras]
qiskit = ["qiskit"]
cirq = ["cirq"]
qsharp = ["qsharp"]

[tool.poetry.dev-dependencies]
pre-commit = "^2.7.1"
commitizen = "2.17.3"
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.790"
data-science-types = "^0.2.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
