### ISSUE TITLE
cz bump ignores custom bump rules

### ISSUE THREAD

**Issue by hoefling** [commitizen-tools/commitizen#448]
## Description

Setting `bump_pattern` or `bump_map` in config (what should be supported according to [Custom bump rules](https://commitizen-tools.github.io/commitizen/customization/#custom-bump-rules) section) has no effect whatsoever.

## Steps to reproduce

Create a new git repo with this config:

<details>
  <summary>pyproject.toml</summary>
  
  ```toml
  [tool.poetry]
  name = "fizz"
  version = "0.4.3"

  [tool.poetry.dependencies]
  python = "^3.9"

  [tool.poetry.dev-dependencies]

  [build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"

  [tool.commitizen]
  version = "0.4.3"
  tag_format = "$version"
  version_files = ["pyproject.toml:version"]
  changelog_start_rev = "0.4"
  changelog_incremental = true
  update_changelog_on_bump = true
  bump_pattern = "^spam:.+"
  bump_map = {"spam" = "PATCH"}
  ```
 </details>

add tags 0.4, 0.4.3 and add a sample commit with message `spam: eggs`:
```sh
$ git tag -a 0.4 -m foo
$ git tag -a 0.4.3 -m bar
$ touch foo.txt && git add foo.txt && git commit -m 'spam: eggs'
```

## Current behavior
```sh
$ cz bump --dry-run
bump: version 0.4.3 → 0.4.3
tag to create: 0.4.3
increment detected: None
```

## Desired behavior
```sh
$ cz bump --dry-run
bump: version 0.4.3 → 0.4.4
tag to create: 0.4.4
increment detected: PATCH
```

## Environment

```sh
$ cz version --report
Commitizen Version: 2.20.0
Python Version: 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15)
[Clang 6.0 (clang-600.0.57)]
Operating System: Darwin
```
