### ISSUE TITLE
version store strategy: "VERSION" file

### ISSUE THREAD

**Issue by ebuildy** [commitizen-tools/commitizen#461]
## Description

Some projects use a simple ``VERSION`` file to store version, instead of the commiziten YAML file.

## Possible Solution

Add an option ``version_strategy: file``

## Additional context

Many projects use ``VERSION`` file with makefile.

**Comment by Lee-W** [comment]
I believe [version_files](https://commitizen-tools.github.io/commitizen/config/#settings) can solve it.

sample config

```toml
[tool.commitizen]
......
version_files = ['VERSION']
```
