### ISSUE TITLE
Duplicated entry on Changelog

### ISSUE THREAD

**Issue by mmartinortiz** [commitizen-tools/commitizen#467]
## Description

The behaviour described here is normal but produces and undesirable result. Could be that the use I'm doing of `commitizen` is not appropriate, and I'm looking for suggestions to solve the duplication of entries on the changelog.

## Current situation

This is how the Changelog looks after the workflow described bellow:

```text
## Unreleased

### Fix

- Capture incorrect input
- Capture incorrect input
```

## Setup

- Git repository with `master` for production code, `dev` for development, and individual `feature` branches for new features, fixes, etc. - The remote repository is hosted in an enterprise instance of GitLab. 
- In the local repository, `commitizen` is used with `pre-commit` to lint the commit description
- In the remote instance of GitLab, `commitizen` is used to create the Changelog and bump the version, creating a tag.

## Workflow

- In the local feature branch, modify the code and create a commit describing either a feature or a fix. You do your job in only one commit (common for fixes, not that much for features) 
- Push the code to the remote
- [CI] GitLab will run the test for the submitted code
- Merge the feature branch into dev. At this point there are two commits:
  - Your feature or fix, with a message like `fix: Capture incorrect input`
  - The merge commit. GitLab will write a message like: `fix: Capture incorrect input\n\nSee merge request !42`
- [CI] A job is run to update the changelog using `cz changelog`. Here is how the job is written

```yaml

update-changelog:
  stage: release
  image: python:3.8-bullseye
  script:
    - *setup_ssh_and_git
    - git reset --hard origin/dev && git pull --ff
    - pip install -U commitizen==2.20.3
    # This will update the changelog with those changes
    # for "next release". These changes are not automatically
    # commited by commitizen
    - cz changelog
    - git add CHANGELOG.md
    - 'git commit -m "docs: Next release updates"'
    # This "push" will trigger the job again. We can use the option
    # `ci.skip` to avoid that behaviour
    - git push origin -o ci.skip $CI_BUILD_REF_NAME:$CI_COMMIT_REF_NAME
  rules:
    # The changelog will only be updated after merging into dev and
    # not during a merge request event
    - if: $CI_COMMIT_REF_NAME == 'dev' && $CI_PIPELINE_SOURCE != 'merge_request_event'
      changes: *package_changes
```

- Because the last two commits have the `fix: Capture incorrect input` message, two entries are created in the Changelog
- Create a MR from `dev` to `master`
- After merging, a job starts to bump the version and update the changelog

```yaml
tag-master:
  stage: release
  image: python:3.8-bullseye
  script:
    - *setup_ssh_and_git
    - git reset --hard origin/master && git pull --ff
    - pip install -U commitizen==2.20.3
    # Bump the version and update the Changelog. This command will
    # commit the changes
    - cz bump --changelog
    # This push will trigger the job again. We can use the option
    # `ci.skip` to avoid that behaviour. The changes a repushed to
    # `master` and `dev`. In this way, `dev` will also have the new
    # bumped version
    - git push origin -o ci.skip $CI_BUILD_REF_NAME:$CI_COMMIT_REF_NAME
    - git push origin -o ci.skip $CI_BUILD_REF_NAME:dev
    # We finally push the tag with the new version. If there is not
    # a bump version due to the lack of `fix`, `feat` or breaking changes,
    # the tag is not created
    - git push origin $(cz version --project)
  rules:
    - if: $CI_COMMIT_REF_NAME == 'master'
      changes: *package_changes
```

- This last Changelog also contains (obviously) the repeated `fix: capture incorrect input`

Note that if you push more than one commit in your feature branch, GitLab will use the merge request title as commit message. I understand that the behaviour of `commitizen` is the expected one, and that GitLab cannot be blamed for choosing the commit message made by the user as the commit message used for the merge. But I'm looking for suggestions to avoid this edge case that makes an ugly duplicate.

I can always modify the Changelog by hand and remove the duplicated line, but I'm too lazy and I prefer if the software does it for me  😆
