### ISSUE TITLE
pre-commit is not working as expected.

### ISSUE THREAD

**Issue by legacyai** [commitizen-tools/commitizen#469]
Pre-commit is skipping all commit messages. 
I am using following ```.pre-commit-config.yaml```

```
default_stages:
- commit
exclude: .git|.tox|tests|docs
fail_fast: true
repos:
- hooks:
  - id: commitizen
    stages: [commit-msg]
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.3
```
Any idea why so. I am not in main branch.

![image](https://user-images.githubusercontent.com/67182839/148751898-aad05453-1497-40da-a457-c9e519283d5a.png)

**Comment by Lee-W** [comment]
Did you run `pre-commit install --hook-type commit-msg`?

**Comment by awmath** [comment]
I can confirm that it is not working as stated in the docs (pre-commit==2.17.0, commitizen==v2.20.5)
The pre-commit hook won't be triggered (always marked as skipped). And even if it does (with `always_run: true`) it won't work as the input is missing.
This is probably caused by some changes within pre-commit it self as I can't even get the commit-msg output with a custom hook.

Workaround:
```
 - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
        always_run: true
        args: [.git/COMMIT_EDITMSG]
```
