### ISSUE TITLE
Content to be added or fixed

### ISSUE THREAD

**Issue by adam-grant-hendry** [commitizen-tools/commitizen#515]
### Type

- [X] Content inaccurate
- [ ] Content missing
- [ ] Typo

### URL

https://commitizen-tools.github.io/commitizen/bump/

## Problem

The docs state "`fix`+everything else" bumps `PATCH` of the version string per the default `commit_map`.

![image](https://user-images.githubusercontent.com/59346180/169664342-1fa58936-67f1-4564-a590-53198736563d.png)

However, this is not the case:

https://github.com/commitizen-tools/commitizen/blob/79165119817cbd0aef25434a85dcbffa3a13acbb/commitizen/defaults.py#L78-L80

Only `fix`, `refactor`, and `perf` bump `PATCH`, leaving out `docs`, `style`, `test`, `build`, and `ci`, which don't bump any part of the version.

Not only are the docs incorrect, but this is out of step with [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/#summary). Additional commit types are permitted by the specification (e.g. `commitizen` appears to be using the [Angular Convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) by default), but no guidance on version bumping is given for these addition types. Where a commit type bumps or does not bump a version, this should be explicitly stated (e.g. the commit message instructions for `fix` has `Correlates with PATCH in SemVer`, but not `refactor` or `perf`, leaving one to believe these do nothing). 

## Recommendations:

1. **(PREFERRED; Conventiona Commit spec)**: Only `feature` and `fix` should be in the default `commit_map` per [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/#summary). `refactor` and `perf` should not bump `PATCH`. The Angular types `refactor`, `perf`, `docs`, `style`, `test`, `build`, and `ci` should be removed from the default commit types.

1. **(ALTERNATIVE; Angular Convention, but explicit messaging): `refactor` and `perf` should not bump `PATCH`. The commit message instructions for `refactor`, `perf`, `docs`, `style`, `test`, `build`, and `ci` should add `Correlates with no version bump in SemVer`. In addition, the docs should clearly state the  [Angular Convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) commit types are included in `cz c` by default.

**Comment by adam-grant-hendry** [comment]
Here's what I'm thinking:

[cz-emoji](https://github.com/adam-grant-hendry/cz-emoji)

**Comment by Lee-W** [comment]
I'm good with 1. @Woile what do you think?

**Comment by Woile** [comment]
I think alternatives like the `cz-emoji` are good, and it should be added to the Third party templates section (there's already one, but it's not the same as this one).

I do think we should update the docs to reflect the current behavior (fix, refactor and perf are patch, not everything).

Regarding option 1, it would be a breaking change. So we should be very careful. I personally have some conflicts with using just feat and fix. 

Here some thought to discuss:

1. In practical terms, when you use `perf`, it means you made a performance improvement and you want it to be released, thus you want to bump somehow your release, right?
2. If you make a performance improvement, and you only have fix or feat, under which category does it fit? I don't really know, but I know I want it released under PATCH because nothing really changes for the user.
3. What do you do in the situations where you don't want to bump the version? I like having a set of "pre-existing" types (build, ci, perf, docs) that do not create a bump when pushing a commit.

I would like to be more compliant with the spec, but the current setup has been working fine for me. Thoughts?

**Comment by adam-grant-hendry** [comment]
The most important tasks would be to

- Correct the documentation (state what change types bump versions and that `commitizen` includes `Angular Convention` types by default)
- Add notes in commit message instructions to identify what version bump occurs with all change types (e.g. `Correlates with no version bump in SemVer`)

This would match the current (author-intended) behavior of the package.

> Here some thought to discuss:
> 
> 1. In practical terms, when you use `perf`, it means you made a performance improvement and you want it to be released, thus you want to bump somehow your release, right?
> 2. If you make a performance improvement, and you only have fix or feat, under which category does it fit? I don't really know, but I know I want it released under PATCH because nothing really changes for the user.
> 3. What do you do in the situations where you don't want to bump the version? I like having a set of "pre-existing" types (build, ci, perf, docs) that do not create a bump when pushing a commit.
> 
> I would like to be more compliant with the spec, but the current setup has been working fine for me. Thoughts?

The purpose of `commitizen` (to my knowledge) is 

- to enforce a consistency in commit messages
- to parse commit messages to determine if versions should be bumped and/or what should go in the changelog

The primary purpose of `Semver` is dependency management. The numbers in the version string identify behavioral changes affecting the end user. Since `Semver` only uses 3 (MAJOR, MINOR, PATCH), this is why `Conventional Commits` only identifies 3 (BREAKING CHANGE, feat, fix).

To answer your questions:

- The behavior MINOR changes are intended to capture are additions/deletions
- The behavior PATCH changes are intended to capture are modifications to existing items that affect their behavior

Regarding 1 & 2:

A performance improvement could either be a feature or a fix.

- If it is above what the current state of the code offers (makes things faster, uses less memory), it is an addition.
- If it is trying to bring things back to the expected state of the system (e.g. a previous feature/fix degraded the performance of item x/y/z where performance is intended by the author and expected by end users depending on it), then it is a fix.

For this, I use scope to identify the nature of the change so that I as the author can choose whether it should bump MINOR or PATCH, rather than always force it to a particular kind of change:

```
feat(perf,speed): improve speed of `x`
```

I am also of the opinion that documentation should be treated like code and is perhaps more valuable than your code base. Documentation is outward facing (the end user relies on it; it is a dependency). If you fix an error (even typos), then it is a fix and PATCH should bump. If you add a feature to your documentation, it deserves a MINOR bump. Again, I use scope to identify the nature of the change. And, as with dependency managers that need to look at version bumps to see whether to include or exclude them, a dependency manager could look at a documentation bump and decide whether or not to include it.

I mention the above because it is confusing that one would have a separate `docs` type that bumps nothing, but that in practice you should really be doing `feat(docs)` or `fix(docs)`. (As an aside, people submit Issues for doc requests and fixes all the time (like me!), so these should be treated like features and fixes linked to the issue)

Regarding 3:

This is where a 3rd option, like `refactor`, comes into play. The term is literally derived from math:

- When you refactor `x^2 + 2x + 1` into `(x+1)^2`, you are not changing the behavior or meaning of the terms. In fact, this is called an identity in mathematics because you can literally replace one term for the other to get the exact same behavior.

Refactors should never bump versions, otherwise they are not refactors. If in refactoring you add something or modify something, then those constitute a MINOR and PATCH bump, respectively.

**Comment by adam-grant-hendry** [comment]
The **tl;dr** for me is

- version bumps should be a consequence of a behavioral change to your code
- a release is separate from a version bump and is a decision made by the author(s) and/or maintainer(s)

**Comment by adam-grant-hendry** [comment]
@Lee-W @Woile Would also be good to add to the docs whether configuration files extend existing behavior or completely override it. As it stands, I don't know if I need to specify all items listed in the [configuration table](https://commitizen-tools.github.io/commitizen/customization/#customize-configuration) or only some.

e.g. After digging through the docs, for customizing through classes, I found

> Inherit from BaseCommitizen, and you must define questions and message. The others are optional.

but there are no such instructions for customizing through a config file. I don't know what I must config and what is optional.

**Comment by adam-grant-hendry** [comment]
@Lee-W @Woile Your `TOML` is also wrong. You have to use `single-quotes` with regular expressions to interpret the strings as literals, or you have to escape back-slashes.

**Comment by adam-grant-hendry** [comment]
> @Lee-W @Woile Your `TOML` is also wrong. You have to use `single-quotes` with regular expressions to interpret the strings as literals, or you have to escape back-slashes.

Actually, nvm. My bad. I think they're right. They look escaped.

**Comment by adam-grant-hendry** [comment]
@Lee-W @Woile Lastly, I also want to say "THANK YOU!!!" for this great package! :tada:

Below is my `pyproject.toml` using standard `commitizen` (no emojis) that meets what I've been talking about above. Three things worth noting:

1. Version `2.20.0` does not have the `commit_parser` option, which is necessary for `CHANGELOG.md` to be properly rendered. Your docs don't have a version attached to them, so I am only able to see docs for the latest version (important, say, for those reverting to version `2.20.0` due to Issue #510 ). So, I bumped back up to `2.27.0`.

2. It would be nice to have an option added that generates a `CHANGELOG.md` header (with `markdownlint` without a header, you get an [`MD041` error](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md041). This is what I have (borrowed from `Keep a Changelog`):

```markdown
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this project adheres to 
[Semantic Versioning](https://semver.org/spec/v2.0.0.html).

Since this project adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), the change types
here match those in the commit messages:

- `Feat` for added/removed/deprecated features
- `Fix` for changed/modified items
- `Refactor` for changes not affecting behavior
```

3. It would be nice if there was a way to customize a third-party plugin. For instance, it would be nice if I could customize `commitizen_emoji` without having to create a separate plugin.

### TOML Configuration:

```toml
[tool.commitizen]
name = "cz_customize"
version = "0.2.0"
version_files = [
    "myu_proj/__version__.py",
    "pyproject.toml:version"
]
update_changelog_on_bump = true
changelog_start_rev = '0.2.0'
annotated_tag = true
tag_format = "$version"

[tool.commitizen.customize]
message_template = "{{change_type}}({{scope}}){% if is_breaking_change == true %}!{% endif %}: {{subject}}{% if body %}\n\n{{body}}{% endif %}{% if footer %}\n\n{% if is_breaking_change == true %}BREAKING CHANGE: {% endif %}{{footer}}{% endif %}"
bump_pattern = '^(feat|fix)(\(.+\))?(!)?'
bump_map = { break = "MAJOR", feat = "MINOR", fix = "PATCH" }
change_type_order = ["BREAKING CHANGE", "feat", "fix"]
commit_parser = '(?P<change_type>feat|fix|refactor)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?:\s(?P<message>.*)?'
changelog_pattern = '^(feat|fix|refactor)?(!)?'

[[toml.commitizen.customize.change_type_map]]
"feat" = "Feat"
"fix" = "Fix"
"refactor" = "Refactor"

[[tool.commitizen.customize.questions]]
name = "change_type"
type = "list"
message = "Select the type of change you are committing"
choices = [
    { value = "feat", name = "feat: (Bumps MINOR) Add/remove an item/feature" },
    { value = "fix", name = "fix: (Bumps PATCH) Fix/modify an existing item/feature" },
    { value = "refactor", name = "refactor: (Bumps nothing) Reorganizes item(s); not a 'feat' or 'fix'" },
]

[[tool.commitizen.customize.questions]]
name = "scope"
type = "input"
message = "Scope. Enter the scope of the change, category first (docs/test/ci/build/perf), followed by class or file name if applicable (comma-separted, no spaces):\n"

[[tool.commitizen.customize.questions]]
name = "subject"
type = "input"
message = "Subject. Enter the short summary of the change (imperative tone, lowercase, no period):\n"

[[tool.commitizen.customize.questions]]
name = "is_breaking_change"
type = "confirm"
message = "Is this a BREAKING CHANGE (backwards incompatible)? (Bumps MAJOR; default: N):\n"
default = false

[[tool.commitizen.customize.questions]]
name = "body"
type = "input"
message = "Body. Enter complete details about the change (use full sentences with proper grammar): (press [enter] to skip):\n"

[[tool.commitizen.customize.questions]]
name = "footer"
type = "input"
message = "Footer. Reference any Issues this change addresses. If a BREAKING CHANGE, enter details. (press [enter] to skip):\n"
```
