### ISSUE TITLE
Bump commits violates against commitizen

### ISSUE THREAD

**Issue by anmoel** [commitizen-tools/commitizen#523]
### Description

Hello, 

i installed the conventional-pre-commit hook.
After that i tried to create a release with `cz bump`. It fails because the commit message is not a valid conventional commit.
I expects that commitizen generates only conventional commits, but "bump" is not a valid cmmit type

### Steps to reproduce

1. install pre-commit hook:
```
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
```
2. run `cz bump --changelog`

### Current behavior

bump commit messages starting always with "bump:"

### Desired behavior

bump commit messages are valid conventional commits

### Screenshots

![image](https://user-images.githubusercontent.com/23420759/173006110-72554f6c-b630-4055-bb81-f4da0061035c.png)

### Environment

Commitizen Version: 2.27.1
Python Version: 3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]
Operating System: Darwin
