### ISSUE TITLE
cz_customize using more than first line of commit in changelog

### ISSUE THREAD

**Issue by whoracle** [commitizen-tools/commitizen#524]
### Description

First off: I'm not sure if this is a bug, PEBKAC or missing documentation.

When using cz changelog with cz_customize and a multiline `message_template`, the changelog contains each line of a commit as an entry, as opposed to only the first line of each commit.

From my understanding, this is because of the usage of re.MULTILINE | re.DOTALL here:
https://github.com/commitizen-tools/commitizen/blob/afa0d93544405bb0a871b5072e0a814720d933be/commitizen/changelog.py#L80

I found no way of changing this behaviour. No modifications to the regex in question has worked for me, and I can't find anything in the documentation about this.

### Steps to reproduce

1. Use the following .cz.yaml:
```yaml
commitizen:
  annotated_tag: true
  bump_message: "bump: release $current_version \u2192 $new_version"
  changelog_file: CHANGELOG.md
  customize:
    bump_map:
      break: MAJOR
      bugfix: PATCH
      docs: PATCH
      feature: MINOR
      hotfix: PATCH
      perf: MINOR
      refactor: PATCH
      style: PATCH
      test: MINOR
    bump_pattern: ^(break|feature|fix|hotfix|docs|performance|refactor|test|style)
    change_type_map:
      break: Break
      bugfix: Fix
      docs: Docs
      feature: Feature
      hotfix: Hotfix
      performance: Performance
      refactor: Refactor
      style: Style
      test: Test
    change_type_order:
    - BREAKING CHANGE
    - docs
    - bugfix
    - hotfix
    - feature
    - refactor
    - performance
    - test
    - style
    changelog_pattern: ^(break|bump|feature|bugfix|hotfix|docs|performance|refactor|test|style)?(!)?
    commit_parser: ^(?P<change_type>feature|bugfix|hotfix|docs|performance|refactor|test|style):\s(?P<message>.*)?
    example: 'feature: this feature enable customize through config file'
    message_template: '{{change_type}}: {{message}}


{% if jira_ticket %} [{{jira_ticket}}]{% endif %}'
    questions:
    - choices:
      - name: 'feature: A new feature'
        value: feature
      - name: 'bugfix: A bug fix'
        value: bugfix
      - name: 'hotfix: An emergency fix'
        value: hotfix
      - name: 'docs: A change to documentation'
        value: docs
      - name: 'performance: An performance improvement'
        value: performance
      - name: 'refactor: Code refactoring'
        value: refactor
      - name: 'test: A change to tests'
        value: test
      - name: 'style: A change to the code style'
        value: style
      - name: 'break: A BREAKING CHANGE'
        value: break
      message: Select the type of change you are committing
      name: change_type
      type: list
    - message: 'Commit Message:'
      name: message
      type: input
    - message: 'JIRA Ticket (leave empty to skip):'
      name: jira_ticket
      type: input
    schema: '<type>: <body>'
    schema_pattern: (break|bump|feature|bugfix|hotfix|docs|performance|refactor|test|style):(\s.*)
  name: cz_customize
  style:
  - - qmark
    - fg:#ff9d00 bold
  - - question
    - bold
  - - answer
    - fg:#ff9d00 bold
  - - pointer
    - fg:#ff9d00 bold
  - - highlighted
    - fg:#ff9d00 bold
  - - selected
    - fg:#cc5454
  - - separator
    - fg:#cc5454
  - - instruction
    - ''
  - - text
    - ''
  - - disabled
    - fg:#858585 italic
  tag_format: $major.$minor.$patch
  update_changelog_on_bump: true
  use_shortcuts: true
  version: 1.0.0
```
2. Create a feature commit with a message `foo` and a jira ticket number `bar`
3. run `cz ch --dry-run`

### Current behavior

cz changelog (and by extension, cz bump) creates one line for each line in the commit:

`cz changelog --dry-run`
```md
## Unreleased


- feature: foo
- [bar]
```

### Desired behavior

cz changelog should only produce one line from the commit header:

`cz changelog --dry-run`
```md
## Unreleased


- feature: foo
```

### Environment

Commitizen Version: 2.20.2
Python Version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Operating System: Linux
