### ISSUE TITLE
pre-commit duplicate entries in output

### ISSUE THREAD

**Issue by Berk-Tosun** [commitizen-tools/commitizen#569]
### Description

I have a new project where I want to use the .pre-commit-config.yaml below. When I make a commit, hooks of type pre-commit are reported twice. Please see current/expected behavior.

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: no-commit-to-branch
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
    hooks:
      - id: commitizen
  ```

I have opened an [issue at pre-commit repository yesterday.](https://github.com/pre-commit/pre-commit/issues/2494) Based on the limited feedback, I modified commitizen entry:

```yaml
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
    hooks:
      - id: commitizen
        stages: [pre-commit]
  ```

No changes in the output.

### Steps to reproduce

0. it is a new project (git init, fresh venv with python3.8.7)
1. pip install pre-commit
2. pre-commit install -t pre-commit -t commit-msg --install-hooks
3. git add
4. git commit

### Current behavior

(venv) ...>git commit -m "feat(main): add fun"
black....................................................................Passed
flake8...................................................................Passed
bandit...................................................................Passed
isort....................................................................Passed
fix end of files.........................................................Passed
don't commit to branch...................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
bandit...............................................(no files to check)Skipped
isort................................................(no files to check)Skipped
don't commit to branch...................................................Passed
commitizen check.........................................................Passed
[ad 0e915e7] feat(main): add fun
12 files changed, 450 insertions(+)
...

### Desired behavior

(venv) ...>git commit -m "feat(main): add fun"
black....................................................................Passed
flake8...................................................................Passed
bandit...................................................................Passed
isort....................................................................Passed
fix end of files.........................................................Passed
don't commit to branch...................................................Passed
commitizen check.........................................................Passed
[ad 0e915e7] feat(main): add fun
12 files changed, 450 insertions(+)
...

### Environment

- commitizen version: 2.32.2
- python version: 3.8.7
- operating system: Windows
