### ISSUE TITLE
Add option --config to set the pyproject.toml configuration file path.

### ISSUE THREAD

**Issue by thomasfinchbr** [commitizen-tools/commitizen#656]
### Description

I was not able to find how to use commitizen with a pyproject.toml file that is not in the root folder.

Thus I would like to suggest the addition of the configuration option --config that could be used in pre-commit config like this:

```
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.31.0
    hooks:
    -   id: commitizen
        additional_dependencies: ['toml']
        stages: [commit-msg]
        args:
        - --config=config/pyproject.toml
```
