### ISSUE TITLE
--major-version-zero is meaningless for current version 3.0.0

### ISSUE THREAD

**Issue by yajo** [commitizen-tools/commitizen#658]
### Description

Cannot bump because of the error.

### Steps to reproduce

With this `.cz.toml`:

```toml
[tool.commitizen]
annotated_tag = true
changelog_incremental = true
major_version_zero = true
tag_format = "v$version"
update_changelog_on_bump = true
version = "3.0.0"
```

Run `cz bump --retry`.

### Current behavior

Error:

    --major-version-zero is meaningless for current version 3.0.0

### Desired behavior

Bumps correctly. If that flag is meaningless, just ignore it and go on.

I maintain the `.cz.toml` file from a template, so it is applied to all of my projects. I expect that configuration to work, regardless whether the project already reached 1.0.0 or not. Obviously it's meaningless for a project in 3.0.0, but that doesn't mean I can't bump anymore!

### Environment

```
➤ cz version
2.37.0
```
