### ISSUE TITLE
Support replacing a placeholder string when bumping the version

### ISSUE THREAD

**Issue by edgarrmondragon** [commitizen-tools/commitizen#809]
### Description

I'm using [Sphinx](https://www.sphinx-doc.org) to document my Python project, which has a [`versionadded` and `versionchanged` _directives_](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded) for rendering the version a feature was added.

For example:

```python
def a_new_function():
  """A simple function.

  .. versionadded:: 0.1.0
  .. versionchanged:: 0.1.1  (could also be 0.2.0 if some features landed before the release)
  Return float.
  """
  return 1.0
```

The problem is, I don't always know what the next version will be, which most of the time is either a patch or a minor bump, so I'd like to configure commitizen with custom strings that it can change and replace with the new version in the project tree, so I can do something like:

```python
def a_new_function():
  """A simple function.

  .. versionadded:: 0.1.0
  .. versionchanged:: NEXT_VERSION
  """
  return 1
```

without having to think what the next version will be. 

### Possible Solution

Perhaps something like this:

```toml
[tool.commitizen]
replace_with_version = "NEXT_VERSION"
```

### Additional context

In the past I've used a similar tool called [Changie](https://changie.dev) that supports a [`replacements`](https://changie.dev/config/#config-replacements) option:

```yaml
# .changie.yaml
- path: src/mylib/client.py
  find: "NEXT_VERSION"
  replace: "{{.VersionNoPrefix}}"
```
