### ISSUE TITLE
cz bump cannot find version scheme "semver" after upgrade

### ISSUE THREAD

**Issue by snellejelle99** [commitizen-tools/commitizen#841]
### Description

After upgrading from 3.8.0 to 3.8.2 i get the following error:
```
$ cz bump --dry-run
Version scheme "semver" unknown.
```

### Steps to reproduce

1. pip install commitizen --upgrade
2. cz bump --dry-run

### Current behavior

The following error is given:
`Version scheme "semver" unknown.`

### Desired behavior

cz bump works as its supposed to

### Environment

```
$ cz version
3.8.2

$ python --version
Python 3.11.5

$ python -c "import platform; print(platform.system())"
Windows

$ cz version --report
Commitizen Version: 3.8.2
Python Version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Operating System: Windows
```

YAML config:
```
---
commitizen:
  name: cz_conventional_commits
  tag_format: v$major.$minor.$patch$prerelease.$devrelease
  version: 2.0.2
  version_files:
  - source/OptionsManager/OptionMacros.h:FIRMWARE_VERSION_CSTRING
  - source/doxygen/Doxyfile:PROJECT_NUMBER
  version_scheme: semver
  update_changelog_on_bump: true
  changelog_merge_prerelease: true
  changelog_incremental: true
```
