### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by edgarrmondragon** [commitizen-tools/commitizen#857]
### Description

Python 3.7 reached its EOL June 27th 2023.

This could also be an opportunity to remove the upper dependency bound and just declare support for `>=3.8`

### Possible Solution

Use

```toml
[tool.poetry.dependencies]
python = ">=3.8"
```

and update dependencies accordingly so the upper bound can be removed.

### Additional context

I can work on a PR if the maintainers are interested.
