### ISSUE TITLE
Change default `bump_message` for plugin

### ISSUE THREAD

**Issue by ghisvail** [commitizen-tools/commitizen#938]
### Description

I designed a [Commitizen plugin](https://github.com/ghisvail/cz-pydata) and would like to implement a restriction on bump commits.

So far, I know I can use:

```toml
# pyproject.toml

[tool.commitizen]
name = "cz_pydata"
bump_message = "REL: Release version $new_version"
```

But it would be up to individual projects to explicitly override `bump_message` to get `cz bump --changelog` to produce a bump message compliant with the PyData spec.

### Possible Solution

Instead, I would like to set this template as default for `cz_pydata` so that configuring the project with:

```toml
# pyproject.toml

[tool.commitizen]
name = "cz_pydata"
```

and running `cz bump --changelog` would produce a commit formatted as `REL: Release version $new_version`.

Even better if `bump_message` remains overridable for projects using additional markers like `[skip ci]`.
